import type { Metadata } from "next"
import Navbar from "@/components/Navbar"
import "@/styles/globals.css"
import { Lexend } from "next/font/google"

const lexend = Lexend({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={lexend.className}>
        <main className='h-screen flex flex-col justify-center items-center'>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}
